spring:
  datasource:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true